---
version: '3'
services:
  postgresql:
    container_name: pgsql
    image: "docker.io/library/postgres:latest"
    volumes:
      - "./data/:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: s3krAt
