---
version: '3'
services:
  postgresql:
    image: "docker.io/library/postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: amari
      POSTGRES_PASSWORD: s3krAt
  redis:
    image: "docker.io/library/redis:latest"
    ports:
      - "6379:6379"
  zookeeper:
    image: "docker.io/library/zookeeper:latest"
    ports:
      - "2181:2181"
  kibana:
    image: "docker.io/library/kibana:7.5.0"
    ports:
      - "5601:5601"
    volumes:
      - "./search/kibana.yml:/usr/share/kibana/config/kibana.yml"
  elasticsearch:
    image: "docker.io/library/elasticsearch:7.5.0"
    ports:
      - "9300:9300"
      - "9200:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - "./search/elasticsearch.yml:/config/elasticsearch.yml"
