---
version: '3'
services:
  postgresql:
    image: "docker.io/bitnami/postgresql:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DATABASE: amari
      POSTGRES_USERNAME: amari
      POSTGRES_PASSWORD: s3krAt
  redis:
    image: "docker.io/library/redis:latest"
    ports:
      - "6379:6379"
  phpredisadmin:
    image: "docker.io/erikdubbelboer/phpredisadmin"
    ports:
      - "9736:80"
  zookeeper:
    image: "docker.io/bitnami/zookeeper:latest"
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
  zoonavigator:
    image: "docker.io/elkozmon/zoonavigator"
    ports:
      - "9000:9000"
    environment:
      AUTO_CONNECT_CONNECTION_STRING: zookeeper
  kibana:
    image: "docker.io/library/kibana:7.5.0"
    ports:
      - "5601:5601"
    volumes:
      - "./search/kibana.yml:/usr/share/kibana/config/kibana.yml"
  elasticsearch:
    image: "docker.io/library/elasticsearch:7.5.0"
    ports:
      - "9300:9300"
      - "9200:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - "./search/elasticsearch.yml:/config/elasticsearch.yml"
